/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as CptReferenceRouteImport } from './routes/cpt-reference'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiTrainingRouteImport } from './routes/ai-training'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilesIdRouteImport } from './routes/files.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminFieldsRouteImport } from './routes/admin.fields'
import { Route as AdminCptRouteImport } from './routes/admin.cpt'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const CptReferenceRoute = CptReferenceRouteImport.update({
  id: '/cpt-reference',
  path: '/cpt-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTrainingRoute = AiTrainingRouteImport.update({
  id: '/ai-training',
  path: '/ai-training',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIdRoute = FilesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FilesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFieldsRoute = AdminFieldsRouteImport.update({
  id: '/admin/fields',
  path: '/admin/fields',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCptRoute = AdminCptRouteImport.update({
  id: '/admin/cpt',
  path: '/admin/cpt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-training': typeof AiTrainingRoute
  '/auth': typeof AuthRoute
  '/claims': typeof ClaimsRoute
  '/cpt-reference': typeof CptReferenceRoute
  '/exports': typeof ExportsRoute
  '/files': typeof FilesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cpt': typeof AdminCptRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/files/$id': typeof FilesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-training': typeof AiTrainingRoute
  '/auth': typeof AuthRoute
  '/claims': typeof ClaimsRoute
  '/cpt-reference': typeof CptReferenceRoute
  '/exports': typeof ExportsRoute
  '/files': typeof FilesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cpt': typeof AdminCptRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/files/$id': typeof FilesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-training': typeof AiTrainingRoute
  '/auth': typeof AuthRoute
  '/claims': typeof ClaimsRoute
  '/cpt-reference': typeof CptReferenceRoute
  '/exports': typeof ExportsRoute
  '/files': typeof FilesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cpt': typeof AdminCptRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/files/$id': typeof FilesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/ai-training'
    | '/auth'
    | '/claims'
    | '/cpt-reference'
    | '/exports'
    | '/files'
    | '/settings'
    | '/upload'
    | '/admin/audit'
    | '/admin/cpt'
    | '/admin/fields'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/users'
    | '/files/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/ai-training'
    | '/auth'
    | '/claims'
    | '/cpt-reference'
    | '/exports'
    | '/files'
    | '/settings'
    | '/upload'
    | '/admin/audit'
    | '/admin/cpt'
    | '/admin/fields'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/users'
    | '/files/$id'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/ai-training'
    | '/auth'
    | '/claims'
    | '/cpt-reference'
    | '/exports'
    | '/files'
    | '/settings'
    | '/upload'
    | '/admin/audit'
    | '/admin/cpt'
    | '/admin/fields'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/users'
    | '/files/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AiTrainingRoute: typeof AiTrainingRoute
  AuthRoute: typeof AuthRoute
  ClaimsRoute: typeof ClaimsRoute
  CptReferenceRoute: typeof CptReferenceRoute
  ExportsRoute: typeof ExportsRoute
  FilesRoute: typeof FilesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCptRoute: typeof AdminCptRoute
  AdminFieldsRoute: typeof AdminFieldsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpt-reference': {
      id: '/cpt-reference'
      path: '/cpt-reference'
      fullPath: '/cpt-reference'
      preLoaderRoute: typeof CptReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-training': {
      id: '/ai-training'
      path: '/ai-training'
      fullPath: '/ai-training'
      preLoaderRoute: typeof AiTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$id': {
      id: '/files/$id'
      path: '/$id'
      fullPath: '/files/$id'
      preLoaderRoute: typeof FilesIdRouteImport
      parentRoute: typeof FilesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fields': {
      id: '/admin/fields'
      path: '/admin/fields'
      fullPath: '/admin/fields'
      preLoaderRoute: typeof AdminFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cpt': {
      id: '/admin/cpt'
      path: '/admin/cpt'
      fullPath: '/admin/cpt'
      preLoaderRoute: typeof AdminCptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FilesRouteChildren {
  FilesIdRoute: typeof FilesIdRoute
}

const FilesRouteChildren: FilesRouteChildren = {
  FilesIdRoute: FilesIdRoute,
}

const FilesRouteWithChildren = FilesRoute._addFileChildren(FilesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  AiTrainingRoute: AiTrainingRoute,
  AuthRoute: AuthRoute,
  ClaimsRoute: ClaimsRoute,
  CptReferenceRoute: CptReferenceRoute,
  ExportsRoute: ExportsRoute,
  FilesRoute: FilesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCptRoute: AdminCptRoute,
  AdminFieldsRoute: AdminFieldsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
