/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CptReferenceRouteImport } from './routes/cpt-reference'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiTrainingRouteImport } from './routes/ai-training'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminCptRouteImport } from './routes/admin.cpt'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CptReferenceRoute = CptReferenceRouteImport.update({
  id: '/cpt-reference',
  path: '/cpt-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTrainingRoute = AiTrainingRouteImport.update({
  id: '/ai-training',
  path: '/ai-training',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCptRoute = AdminCptRouteImport.update({
  id: '/admin/cpt',
  path: '/admin/cpt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-training': typeof AiTrainingRoute
  '/auth': typeof AuthRoute
  '/claims': typeof ClaimsRoute
  '/cpt-reference': typeof CptReferenceRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/admin/cpt': typeof AdminCptRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-training': typeof AiTrainingRoute
  '/auth': typeof AuthRoute
  '/claims': typeof ClaimsRoute
  '/cpt-reference': typeof CptReferenceRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/admin/cpt': typeof AdminCptRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-training': typeof AiTrainingRoute
  '/auth': typeof AuthRoute
  '/claims': typeof ClaimsRoute
  '/cpt-reference': typeof CptReferenceRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/admin/cpt': typeof AdminCptRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/ai-training'
    | '/auth'
    | '/claims'
    | '/cpt-reference'
    | '/settings'
    | '/upload'
    | '/admin/cpt'
    | '/admin/settings'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/ai-training'
    | '/auth'
    | '/claims'
    | '/cpt-reference'
    | '/settings'
    | '/upload'
    | '/admin/cpt'
    | '/admin/settings'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/ai-training'
    | '/auth'
    | '/claims'
    | '/cpt-reference'
    | '/settings'
    | '/upload'
    | '/admin/cpt'
    | '/admin/settings'
    | '/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AiTrainingRoute: typeof AiTrainingRoute
  AuthRoute: typeof AuthRoute
  ClaimsRoute: typeof ClaimsRoute
  CptReferenceRoute: typeof CptReferenceRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  AdminCptRoute: typeof AdminCptRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpt-reference': {
      id: '/cpt-reference'
      path: '/cpt-reference'
      fullPath: '/cpt-reference'
      preLoaderRoute: typeof CptReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-training': {
      id: '/ai-training'
      path: '/ai-training'
      fullPath: '/ai-training'
      preLoaderRoute: typeof AiTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cpt': {
      id: '/admin/cpt'
      path: '/admin/cpt'
      fullPath: '/admin/cpt'
      preLoaderRoute: typeof AdminCptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  AiTrainingRoute: AiTrainingRoute,
  AuthRoute: AuthRoute,
  ClaimsRoute: ClaimsRoute,
  CptReferenceRoute: CptReferenceRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  AdminCptRoute: AdminCptRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
